blank_issues_enabled: false  # trueにすると「テンプレートを使わない空issue」を許可する
contact_links:               # テンプレート以外の問い合わせ先を案内できる
  - name: 📖 ドキュメントを読む
    url: https://github.com/disrupt-infocom/infocom-docs/wiki
    about: 不明点がある場合はまずはこちらを参照してください